language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_1bbae009170c_key -iv $encrypted_1bbae009170c_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
