language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
env:
  global:
    secure: NWd+SAx3OLFsfBXPD9CfCOfdOoAjPRnHml0A3yabNRFdL704t+vRGzdDNbQD15d72R034PHeDms0lGaysRA9WYsQsB8UPgOVMP5tl/TT5CQ9aWKlRdea2/rj5atv5MHg5N42aAI+rN0AP6MaOwA9CY62EZzgsGN+2VddnFmsahN/Vmu6VH6A/nEenNifKJKpNrYDmBaxRmvnYgWwDDU9SKF1htLHKwdW0aCWtVy0oC/yPWTfrZ7uXbh4bg9syR9nn0/PlkFzzmybxK5pGVsgPBG5JBPsUMiIMTjlzzVlJhl8SuoIY0eGcOjeJzUqBlBb1IEaFEnF6dB7vf0VywHO2qDzhSbGNbDpikuiyrka8+J+GDIFtNSQKWaR39Rm+QU9uKXk6rqF4fzoQgziT2MELaLvxj44VlHWGe+HYw8qrl/EYyI3Lxwp1PDzMJoi255802m5NATG1yA7CiLF64Cq+o5orSBpRiF0Ku0Z4654iWj9KLXaEVdAG/RhHioowO4PdJDqhmZ2YGq3c8m4UH5nf0MihRYyoYk44IkL/ro6Zh/2dzVd8Umh+qbfhfxil4fn3oj3lI8FLVT00ojN5hvQr0hjp8q/dRJyJ+20f2BojspSuYr/gFUMsoibVxhQvwL3Ad6Pt8XWlBfxja7v5XJjMMdK6R7QxWS9P6AqcWx+Bg4=
