language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_51582b7a99c8_key -iv $encrypted_51582b7a99c8_iv
  -in application.properties.enc -out src/main/resources/application.properties -d
- openssl aes-256-cbc -K $encrypted_37c734d3f559_key -iv $encrypted_37c734d3f559_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
